//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.30 at 10:17:04 AM EDT 
//


package icd10.pcs.definition;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the icd10.pcs.definition package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Operation_QNAME = new QName("", "operation");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _Definition_QNAME = new QName("", "definition");
    private final static QName _Explanation_QNAME = new QName("", "explanation");
    private final static QName _Device_QNAME = new QName("", "device");
    private final static QName _BodySys_QNAME = new QName("", "bodySys");
    private final static QName _Includes_QNAME = new QName("", "includes");
    private final static QName _Version_QNAME = new QName("", "version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: icd10.pcs.definition
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aggregate }
     * 
     */
    public Aggregate createAggregate() {
        return new Aggregate();
    }

    /**
     * Create an instance of {@link ICD10PCSDefinitions }
     * 
     */
    public ICD10PCSDefinitions createICD10PCSDefinitions() {
        return new ICD10PCSDefinitions();
    }

    /**
     * Create an instance of {@link Terms }
     * 
     */
    public Terms createTerms() {
        return new Terms();
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link Axis }
     * 
     */
    public Axis createAxis() {
        return new Axis();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link DeviceAggregation }
     * 
     */
    public DeviceAggregation createDeviceAggregation() {
        return new DeviceAggregation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "operation")
    public JAXBElement<String> createOperation(String value) {
        return new JAXBElement<String>(_Operation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "definition")
    public JAXBElement<String> createDefinition(String value) {
        return new JAXBElement<String>(_Definition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "explanation")
    public JAXBElement<String> createExplanation(String value) {
        return new JAXBElement<String>(_Explanation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "device")
    public JAXBElement<String> createDevice(String value) {
        return new JAXBElement<String>(_Device_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bodySys")
    public JAXBElement<String> createBodySys(String value) {
        return new JAXBElement<String>(_BodySys_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "includes")
    public JAXBElement<String> createIncludes(String value) {
        return new JAXBElement<String>(_Includes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

}
