//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.02 at 05:13:37 PM EDT 
//


package icd10.cm.tabular;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the icd10.cm.tabular package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _Desc_QNAME = new QName("", "desc");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _Heading_QNAME = new QName("", "heading");
    private final static QName _Version_QNAME = new QName("", "version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: icd10.cm.tabular
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SevenChrNote }
     * 
     */
    public SevenChrNote createSevenChrNote() {
        return new SevenChrNote();
    }

    /**
     * Create an instance of {@link VisMin }
     * 
     */
    public VisMin createVisMin() {
        return new VisMin();
    }

    /**
     * Create an instance of {@link IntroSection }
     * 
     */
    public IntroSection createIntroSection() {
        return new IntroSection();
    }

    /**
     * Create an instance of {@link Instruction }
     * 
     */
    public Instruction createInstruction() {
        return new Instruction();
    }

    /**
     * Create an instance of {@link VisualImpairment }
     * 
     */
    public VisualImpairment createVisualImpairment() {
        return new VisualImpairment();
    }

    /**
     * Create an instance of {@link InclusionTerm }
     * 
     */
    public InclusionTerm createInclusionTerm() {
        return new InclusionTerm();
    }

    /**
     * Create an instance of {@link CodeFirst }
     * 
     */
    public CodeFirst createCodeFirst() {
        return new CodeFirst();
    }

    /**
     * Create an instance of {@link Includes }
     * 
     */
    public Includes createIncludes() {
        return new Includes();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link CodeAlso }
     * 
     */
    public CodeAlso createCodeAlso() {
        return new CodeAlso();
    }

    /**
     * Create an instance of {@link Diag }
     * 
     */
    public Diag createDiag() {
        return new Diag();
    }

    /**
     * Create an instance of {@link SectionIndex }
     * 
     */
    public SectionIndex createSectionIndex() {
        return new SectionIndex();
    }

    /**
     * Create an instance of {@link VisMax }
     * 
     */
    public VisMax createVisMax() {
        return new VisMax();
    }

    /**
     * Create an instance of {@link Excludes1 }
     * 
     */
    public Excludes1 createExcludes1() {
        return new Excludes1();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link Introduction }
     * 
     */
    public Introduction createIntroduction() {
        return new Introduction();
    }

    /**
     * Create an instance of {@link ICD10CMTabular }
     * 
     */
    public ICD10CMTabular createICD10CMTabular() {
        return new ICD10CMTabular();
    }

    /**
     * Create an instance of {@link VisRange }
     * 
     */
    public VisRange createVisRange() {
        return new VisRange();
    }

    /**
     * Create an instance of {@link SectionRef }
     * 
     */
    public SectionRef createSectionRef() {
        return new SectionRef();
    }

    /**
     * Create an instance of {@link UseAdditionalCode }
     * 
     */
    public UseAdditionalCode createUseAdditionalCode() {
        return new UseAdditionalCode();
    }

    /**
     * Create an instance of {@link SevenChrDef }
     * 
     */
    public SevenChrDef createSevenChrDef() {
        return new SevenChrDef();
    }

    /**
     * Create an instance of {@link Excludes2 }
     * 
     */
    public Excludes2 createExcludes2() {
        return new Excludes2();
    }

    /**
     * Create an instance of {@link VisCategory }
     * 
     */
    public VisCategory createVisCategory() {
        return new VisCategory();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "desc")
    public JAXBElement<String> createDesc(String value) {
        return new JAXBElement<String>(_Desc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "heading")
    public JAXBElement<String> createHeading(String value) {
        return new JAXBElement<String>(_Heading_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<Byte> createVersion(Byte value) {
        return new JAXBElement<Byte>(_Version_QNAME, Byte.class, null, value);
    }

}
