//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.02 at 05:13:37 PM EDT 
//


package icd10.cm.tabular;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}desc"/>
 *         &lt;element ref="{}diag"/>
 *         &lt;element ref="{}includes"/>
 *         &lt;element ref="{}excludes1"/>
 *         &lt;element ref="{}excludes2"/>
 *         &lt;element ref="{}notes"/>
 *         &lt;element ref="{}codeFirst"/>
 *         &lt;element ref="{}useAdditionalCode"/>
 *         &lt;element ref="{}codeAlso"/>
 *         &lt;element ref="{}inclusionTerm"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="oldid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descOrDiagOrIncludes"
})
@XmlRootElement(name = "section")
public class Section {

    @XmlElements({
        @XmlElement(name = "inclusionTerm", type = InclusionTerm.class),
        @XmlElement(name = "notes", type = Notes.class),
        @XmlElement(name = "desc", type = String.class),
        @XmlElement(name = "excludes1", type = Excludes1 .class),
        @XmlElement(name = "codeAlso", type = CodeAlso.class),
        @XmlElement(name = "excludes2", type = Excludes2 .class),
        @XmlElement(name = "useAdditionalCode", type = UseAdditionalCode.class),
        @XmlElement(name = "codeFirst", type = CodeFirst.class),
        @XmlElement(name = "diag", type = Diag.class),
        @XmlElement(name = "includes", type = Includes.class)
    })
    protected List<Object> descOrDiagOrIncludes;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String oldid;

    /**
     * Gets the value of the descOrDiagOrIncludes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descOrDiagOrIncludes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescOrDiagOrIncludes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InclusionTerm }
     * {@link Notes }
     * {@link String }
     * {@link Excludes1 }
     * {@link CodeAlso }
     * {@link Excludes2 }
     * {@link UseAdditionalCode }
     * {@link CodeFirst }
     * {@link Diag }
     * {@link Includes }
     * 
     * 
     */
    public List<Object> getDescOrDiagOrIncludes() {
        if (descOrDiagOrIncludes == null) {
            descOrDiagOrIncludes = new ArrayList<Object>();
        }
        return this.descOrDiagOrIncludes;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oldid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldid() {
        return oldid;
    }

    /**
     * Sets the value of the oldid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldid(String value) {
        this.oldid = value;
    }

}
