//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.02 at 05:13:37 PM EDT 
//


package icd10.cm.tabular;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}heading" minOccurs="0"/>
 *         &lt;element ref="{}visMax"/>
 *         &lt;element ref="{}visMin" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "heading",
    "visMax",
    "visMin"
})
@XmlRootElement(name = "visRange")
public class VisRange {

    protected String heading;
    @XmlElement(required = true)
    protected VisMax visMax;
    protected VisMin visMin;

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeading(String value) {
        this.heading = value;
    }

    /**
     * Gets the value of the visMax property.
     * 
     * @return
     *     possible object is
     *     {@link VisMax }
     *     
     */
    public VisMax getVisMax() {
        return visMax;
    }

    /**
     * Sets the value of the visMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisMax }
     *     
     */
    public void setVisMax(VisMax value) {
        this.visMax = value;
    }

    /**
     * Gets the value of the visMin property.
     * 
     * @return
     *     possible object is
     *     {@link VisMin }
     *     
     */
    public VisMin getVisMin() {
        return visMin;
    }

    /**
     * Sets the value of the visMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisMin }
     *     
     */
    public void setVisMin(VisMin value) {
        this.visMin = value;
    }

}
